#!/bin/bash

# Setting up X11 forwarding which utilizes local wifi
echo "-----------------------"
IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
echo "Your IP is set to:" $IP
/opt/X11/bin/xhost + $IP # For Mac OSX Catalina the XQuartz xhost is not in $PATH so full path is needed

IMAGEVERSION=4
IMAGE=vanilla-ubuntu-for-fireworks:${IMAGEVERSION}

# Building commandline
CMD="docker run \
    -it \
    --rm \
    --name fw${IMAGEVERSION} \
    -e DISPLAY=$IP:0 \
    -e XAUTHORITY=/.Xauthority \
    --net host \
    -v ${HOME}/.Xauthority:/.Xauthority"




CMD="${CMD} ${IMAGE}"

# Printing out full docker command used
echo "-----------------------"
echo "Running docker command:"
echo $CMD
echo "-----------------------"
echo "Run Docker Container!"
echo "..."
echo "..."
echo "..."
$CMD
